import { MetreVersion } from '../types/versions';

export const MOCK_VERSIONS: MetreVersion[] = [
  {
    id: 'v5',
    versionNumber: 5,
    label: 'Version actuelle — Ajustement prix menuiserie',
    trigger: 'manual',
    createdAt: '2026-07-24T14:32:00',
    lignesCount: 148,
    totalTTC: 14691000,
    isCurrent: true,
  },
  {
    id: 'v4',
    versionNumber: 4,
    label: 'Sauvegarde avant export — 23 juillet',
    trigger: 'export',
    createdAt: '2026-07-23T09:15:00',
    lignesCount: 147,
    totalTTC: 14210000,
    isCurrent: false,
  },
  {
    id: 'v3',
    versionNumber: 3,
    label: 'Sauvegarde automatique — 10 modifications de prix',
    trigger: 'auto',
    createdAt: '2026-07-22T16:48:00',
    lignesCount: 147,
    totalTTC: 13980000,
    isCurrent: false,
  },
  {
    id: 'v2',
    versionNumber: 2,
    label: "Résultat de l'analyse IA",
    trigger: 'analyse',
    createdAt: '2026-07-22T11:02:00',
    lignesCount: 142,
    totalTTC: null,
    isCurrent: false,
  },
  {
    id: 'v1',
    versionNumber: 1,
    label: 'Version initiale — Projet créé',
    trigger: 'initial',
    createdAt: '2026-07-22T10:58:00',
    lignesCount: 0,
    totalTTC: null,
    isCurrent: false,
  },
];
